-- ═══════════════════════════════════════════════════════════
--  v3.2 Migration: GeneratedDocumentType 확장 + 내용 필드 추가
-- ═══════════════════════════════════════════════════════════

-- A. 원청 직접고용 패키지
ALTER TYPE "GeneratedDocumentType" ADD VALUE IF NOT EXISTS 'SITE_ASSIGNMENT';
ALTER TYPE "GeneratedDocumentType" ADD VALUE IF NOT EXISTS 'WORK_CONDITION_CHANGE';
ALTER TYPE "GeneratedDocumentType" ADD VALUE IF NOT EXISTS 'SAFETY_EDUCATION_NEW_HIRE';
ALTER TYPE "GeneratedDocumentType" ADD VALUE IF NOT EXISTS 'SAFETY_EDUCATION_TASK_CHANGE';
ALTER TYPE "GeneratedDocumentType" ADD VALUE IF NOT EXISTS 'PPE_PROVISION';
ALTER TYPE "GeneratedDocumentType" ADD VALUE IF NOT EXISTS 'SAFETY_PLEDGE';

-- B. 원청 하도급/외주 패키지
ALTER TYPE "GeneratedDocumentType" ADD VALUE IF NOT EXISTS 'SUBCONTRACT_CONTRACT';
ALTER TYPE "GeneratedDocumentType" ADD VALUE IF NOT EXISTS 'SUBCONTRACT_SCOPE';
ALTER TYPE "GeneratedDocumentType" ADD VALUE IF NOT EXISTS 'SUBCONTRACT_PAYMENT_TERMS';
ALTER TYPE "GeneratedDocumentType" ADD VALUE IF NOT EXISTS 'SUBCONTRACT_SAFETY_PROTOCOL';
ALTER TYPE "GeneratedDocumentType" ADD VALUE IF NOT EXISTS 'SUBCONTRACT_DOCUMENT_LIST';
ALTER TYPE "GeneratedDocumentType" ADD VALUE IF NOT EXISTS 'SUBCONTRACT_DISTRIBUTION_REF';

-- C. 사업자 없는 팀장형 예외 세트
ALTER TYPE "GeneratedDocumentType" ADD VALUE IF NOT EXISTS 'TEAM_LEADER_RESPONSIBILITY';
ALTER TYPE "GeneratedDocumentType" ADD VALUE IF NOT EXISTS 'TEAM_SCOPE_CONFIRMATION';
ALTER TYPE "GeneratedDocumentType" ADD VALUE IF NOT EXISTS 'TEAM_SAFETY_COMPLIANCE';
ALTER TYPE "GeneratedDocumentType" ADD VALUE IF NOT EXISTS 'TEAM_DISTRIBUTION_SUBMISSION';
ALTER TYPE "GeneratedDocumentType" ADD VALUE IF NOT EXISTS 'TEAM_RECLASSIFICATION_WARNING';

-- 안전관리 공통
ALTER TYPE "GeneratedDocumentType" ADD VALUE IF NOT EXISTS 'SAFETY_COUNCIL_MINUTES';
ALTER TYPE "GeneratedDocumentType" ADD VALUE IF NOT EXISTS 'SITE_INSPECTION_RECORD';
ALTER TYPE "GeneratedDocumentType" ADD VALUE IF NOT EXISTS 'SUBCONTRACTOR_EDUCATION_RECORD';

-- generated_documents 내용 저장 필드 추가
ALTER TABLE "generated_documents"
  ADD COLUMN IF NOT EXISTS "contentText" TEXT,
  ADD COLUMN IF NOT EXISTS "contentJson" JSONB,
  ADD COLUMN IF NOT EXISTS "status"      TEXT NOT NULL DEFAULT 'DRAFT';

-- filePath 기본값 허용 (기존 NOT NULL 컬럼)
ALTER TABLE "generated_documents"
  ALTER COLUMN "filePath" SET DEFAULT '';
