-- AlterEnum: ContractTemplateType에 MONTHLY_FIXED_EMPLOYMENT, CONTINUOUS_EMPLOYMENT 추가
ALTER TYPE "ContractTemplateType" ADD VALUE IF NOT EXISTS 'MONTHLY_FIXED_EMPLOYMENT';
ALTER TYPE "ContractTemplateType" ADD VALUE IF NOT EXISTS 'CONTINUOUS_EMPLOYMENT';
